name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - dev
      - CI_update
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: Build Linux packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment variables
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
          echo "• GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "• GITHUB_REF_TYPE=$GITHUB_REF_TYPE" # `branch` or `tag`
          echo "• GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "• GITHUB_SHA=$GITHUB_SHA"
          echo "• RUNNER_ARCH=$RUNNER_ARCH"
          echo "• RUNNER_NAME=$RUNNER_NAME"
          echo "• RUNNER_OS=$RUNNER_OS"
          echo "• RUNNER_TEMP=$RUNNER_TEMP"
          echo "• RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
      - name: Install Yarn package manager
        run: |
          npm install -g yarn
          yarn global add node-gyp
      - name: Install necessary dependencies and perform initial checks
        run: |
          yarn install
          yarn lint
      - name: Run "build" script
        if: github.ref_type == 'tag'
        run: yarn run build
      - name: Run "build-latest" script
        if: github.ref_type == 'branch'
        run: yarn run build-latest
      - name: Build Linux binaries
        run: |
          yarn run build:linux
      - name: Prepare release assets
        shell: bash
        run: |
          GIT_COMMIT_LOG=`git log -1 --format='%ci %H %s'`
          PRODUCT_NAME=gSender
          PACKAGE_NAME=`node -e "console.log(require('./src/package.json').name)"`
          PACKAGE_VERSION=`node -e "console.log(require('./src/package.json').version)"`
          mkdir -p releases/linux
          ls -al output
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-x86_64.AppImage" "releases/linux/${PACKAGE_NAME}-${PACKAGE_VERSION}-Linux-Intel-64Bit.AppImage"
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-amd64.deb" "releases/linux/${PACKAGE_NAME}-${PACKAGE_VERSION}-Linux-Intel-64Bit.deb"
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-arm64.AppImage" "releases/linux/${PACKAGE_NAME}-${PACKAGE_VERSION}-Linux-ARM-64Bit.AppImage"
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-arm64.deb" "releases/linux/${PACKAGE_NAME}-${PACKAGE_VERSION}-Linux-ARM-64Bit.deb"
          ls -al output releases/linux
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: "releases/linux/*"

  build-macos:
    name: Build macOS packages
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment variables
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
          echo "• GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "• GITHUB_REF_TYPE=$GITHUB_REF_TYPE" # `branch` or `tag`
          echo "• GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "• GITHUB_SHA=$GITHUB_SHA"
          echo "• RUNNER_ARCH=$RUNNER_ARCH"
          echo "• RUNNER_NAME=$RUNNER_NAME"
          echo "• RUNNER_OS=$RUNNER_OS"
          echo "• RUNNER_TEMP=$RUNNER_TEMP"
          echo "• RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
      - name: Install Yarn package manager and Node Gyp
        run: |
          npm install -g yarn
          yarn global add node-gyp
      - name: Pip setuptools
        run: |
          sudo -H pip install setuptools
      - name: Install necessary dependencies and perform initial checks
        run: |
          yarn install
          yarn lint
      - name: Run "build" script
        if: github.ref_type == 'tag'
        run: yarn run build
      - name: Run "build-latest" script
        if: github.ref_type == 'branch'
        run: yarn run build-latest
      - name: Build macOS binaries
        run: yarn run build:macos
      - name: Prepare release assets
        shell: bash
        run: |
          GIT_COMMIT_LOG=`git log -1 --format='%ci %H %s'`
          PRODUCT_NAME=gSender
          PACKAGE_NAME=`node -e "console.log(require('./src/package.json').name)"`
          PACKAGE_VERSION=`node -e "console.log(require('./src/package.json').version)"`
          mkdir -p releases/macos
          ls -al output
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-x64.dmg" "releases/macos/gSender-${PACKAGE_VERSION}-Mac-Universal.dmg"
          ls -al output releases/macos
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: "releases/macos/*.dmg"

  build-windows:
    name: Build Windows packages
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    steps:
      - name: Prepare VC++ Runtime
        run: choco install -y vcredist2017
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment variables
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
          echo "• GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "• GITHUB_REF_TYPE=$GITHUB_REF_TYPE" # `branch` or `tag`
          echo "• GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "• GITHUB_SHA=$GITHUB_SHA"
          echo "• RUNNER_ARCH=$RUNNER_ARCH"
          echo "• RUNNER_NAME=$RUNNER_NAME"
          echo "• RUNNER_OS=$RUNNER_OS"
          echo "• RUNNER_TEMP=$RUNNER_TEMP"
          echo "• RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
      - name: Install Yarn package manager and Node Gyp
        run: |
          npm install -g yarn
          yarn global add node-gyp
      - name: Install necessary dependencies and perform initial checks
        run: |
          yarn install
      - name: Run "build" script
        if: github.ref_type == 'tag'
        run: yarn run build
      - name: Run "build-latest" script
        if: github.ref_type == 'branch'
        run: yarn run build-latest
      - name: Build Windows binaries
        run: yarn run build:windows
      - name: Prepare release assets
        shell: bash
        run: |
          GIT_COMMIT_LOG=`git log -1 --format='%ci %H %s'`
          PRODUCT_NAME=gSender
          PACKAGE_NAME=`node -e "console.log(require('./src/package.json').name)"`
          PACKAGE_VERSION=`node -e "console.log(require('./src/package.json').version)"`
          mkdir -p releases/windows
          ls -al output
          cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}-x64.exe" "releases/windows/gSender-${PACKAGE_VERSION}-Windows-64Bit.exe"
          ls -al output releases/windows
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: "releases/windows/*.exe"

